version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    ports:
       - "8181:8181"
    environment:
      APP_NAME: MourideXam
      APP_ENV: local
      APP_KEY: base64:AAAL4ergxXkTX+Jsk/5bdceGZXmM9NXJHcBAxRwXlso=
      APP_DEBUG: "true"
      APP_TIMEZONE: UTC
      APP_URL: http://0.0.0.0:8181
      FRONTEND_URL: http://localhost:4200
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      APP_FAKER_LOCALE: en_US
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: mouridEdu_docker
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: bNk3H58lOp3K9jPxPi33ufOkP0EvblV9JNEwoSd1zPBYtLAKAdEAel3usPlwpmMz
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ../MouridEdu_front
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    command: ng serve --host 0.0.0.0 --port 4200
    restart: unless-stopped

  mysql:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mouridEdu_docker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local